version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
